Repository YAPP-19th/iOS-Team-1-Backend, pull requests merged in 2021-12, with the labels that each got.

#95 [YAPPIOS-184] repository로 쓰는 것을 각 service에 맞게 사용하도록 설정
  src/main/java/com/yapp/project/account/service/AccountService.java
  src/main/java/com/yapp/project/batch/job/GroupConfig.java
  src/main/java/com/yapp/project/batch/job/MissionConfig.java
  src/main/java/com/yapp/project/capture/service/CaptureService.java
  src/main/java/com/yapp/project/mission/service/MissionService.java
  src/main/java/com/yapp/project/organization/service/GroupService.java
  src/test/java/com/yapp/project/mission/service/MissionServiceTest.java
Labels: :construction:Refactoring:construction:

#96 [YAPPIOS-185] 회고 작성일 이슈 수정 및 부가요소 리팩토링
  src/main/java/com/yapp/project/aux/content/RetrospectContent.java
  src/main/java/com/yapp/project/retrospect/domain/Retrospect.java
  src/main/java/com/yapp/project/retrospect/domain/dto/RetrospectDTO.java
  src/main/java/com/yapp/project/retrospect/service/RetrospectService.java
  src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
  src/test/java/com/yapp/project/report/template/WeekReportTemplate.java
  src/test/java/com/yapp/project/retrospect/RetrospectServiceTest.java
  src/test/java/com/yapp/project/routine/RoutineTemplate.java
Labels: :construction:Refactoring:construction:

#98 [YAPPIOS-187] 통합테스트시 빌더 부분에 id제거
  src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
  src/main/java/com/yapp/project/aux/test/mission/MissionTemplate.java
  src/main/java/com/yapp/project/aux/test/organization/OrganizationTemplate.java
  src/test/java/com/yapp/project/account/controller/AccountControllerTest.java
  src/test/java/com/yapp/project/account/controller/AuthControllerTest.java
  src/test/java/com/yapp/project/account/service/AccountServiceTest.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
  src/test/java/com/yapp/project/batch/job/GroupConfigTest.java
  src/test/java/com/yapp/project/retrospect/RetrospectServiceTest.java
Labels: :construction:Refactoring:construction:

#99 [YAPPIOS-188] JPA N+1 문제 해결
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
  src/main/java/com/yapp/project/aux/test/capture/CaptureTemplate.java
  src/main/java/com/yapp/project/aux/test/mission/MissionTemplate.java
  src/main/java/com/yapp/project/aux/test/organization/OrganizationTemplate.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
  src/main/java/com/yapp/project/organization/domain/Organization.java
  src/main/java/com/yapp/project/organization/domain/repository/OrganizationRepository.java
  src/test/java/com/yapp/project/batch/job/GroupConfigTest.java
  src/test/java/com/yapp/project/batch/job/MissionConfigTest.java
  src/test/java/com/yapp/project/mission/service/MissionServiceTest.java
  src/test/java/com/yapp/project/organization/domain/repository/OrganizationRepositoryTest.java
Labels: :construction:Refactoring:construction:

#101 [YAPPIOS-191] Mission 관련 레포지토리 테스트케이스 추가
  src/main/java/com/yapp/project/aux/test/organization/OrganizationTemplate.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
  src/test/java/com/yapp/project/mission/domain/repository/MissionRepositoryTest.java
Labels: :construction:Refactoring:construction:

#100 [YAPPIOS-190] JPA N+1(루틴, 회고) 해결 및 타 레포 호출 서비스로 변경
  src/main/java/com/yapp/project/organization/controller/OrganizationController.java
  src/main/java/com/yapp/project/organization/service/GroupService.java
  src/main/java/com/yapp/project/retrospect/domain/RetrospectRepository.java
  src/main/java/com/yapp/project/routine/domain/Routine.java
  src/main/java/com/yapp/project/routine/domain/RoutineRepository.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
  src/test/java/com/yapp/project/organization/service/GroupServiceTest.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
Labels: :construction:Refactoring:construction:

#102 [YAPPIOS-192] 일별 루틴 수행률 응답 수정 및 남은 N+1 해결
  src/main/java/com/yapp/project/retrospect/domain/RetrospectRepository.java
  src/main/java/com/yapp/project/routine/domain/Routine.java
  src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
  src/main/java/com/yapp/project/routine/domain/RoutineRepository.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
Labels: :construction:Refactoring:construction:

#103 [YAPPIOS-194] 테스트 코드 수정 및 JPA 수정
  src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
  src/test/java/com/yapp/project/organization/domain/repository/OrganizationRepositoryTest.java
Labels: :construction:Refactoring:construction:

#104 [YAPPIOS-206] 스웨거에서 getter 함수를 변수로 읽어들이는 현상이 발견되어 수정.
  src/main/java/com/yapp/project/account/domain/dto/SocialDto.java
  src/main/java/com/yapp/project/account/service/AuthService.java
Labels: :construction:Refactoring:construction:, :hammer_and_pick:클라이언트 작업 필요:hammer_and_pick:

#105 [YAPPIOS-208] 알람 토글 설정 변경
  src/main/java/com/yapp/project/account/controller/AccountController.java
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
  src/main/java/com/yapp/project/account/service/AccountService.java
  src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
  src/test/java/com/yapp/project/account/service/AccountServiceTest.java
  src/test/java/com/yapp/project/mission/domain/repository/MissionRepositoryTest.java
  src/test/java/com/yapp/project/mission/service/MissionServiceTest.java
Labels: :construction:Refactoring:construction:, :hammer_and_pick:클라이언트 작업 필요:hammer_and_pick:

#106 [YAPPIOS-207] 알림 리스트 API 구현
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/aux/StatusEnum.java
  src/main/java/com/yapp/project/aux/content/NotificationContent.java
  src/main/java/com/yapp/project/batch/job/ReportNotificationConfig.java
  src/main/java/com/yapp/project/config/exception/notification/NotificationExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/notification/NotificationNotFoundException.java
  src/main/java/com/yapp/project/notification/controller/NotificationController.java
  src/main/java/com/yapp/project/notification/domain/Notification.java
  src/main/java/com/yapp/project/notification/domain/NotificationRepository.java
  src/main/java/com/yapp/project/notification/domain/dto/NotificationResponse.java
  src/main/java/com/yapp/project/notification/service/NotificationService.java
  src/main/java/com/yapp/project/report/controller/ReportController.java
  src/main/java/com/yapp/project/retrospect/controller/RetrospectController.java
  src/main/java/com/yapp/project/routine/controller/RoutineController.java
Labels: SCAFFOLDING:building_construction:, :bangbang:긴급 추가:bangbang:

#107 [YAPPIOS-146] 환경에 따른 설정파일 적용
  .gitignore
  jenkinsfiles/Jenkinsfile_develop
Labels: :construction:Refactoring:construction:

#108 [YAPPIOS-209] 공지사항 관련 기능 추가
  src/main/java/com/yapp/project/aux/StatusEnum.java
  src/main/java/com/yapp/project/aux/content/NoticeContent.java
  src/main/java/com/yapp/project/config/SecurityConfig.java
  src/main/java/com/yapp/project/config/exception/notice/NoticeExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/notice/NoticeNotFoundException.java
  src/main/java/com/yapp/project/notice/controller/NoticeController.java
  src/main/java/com/yapp/project/notice/domain/Notice.java
  src/main/java/com/yapp/project/notice/domain/dto/NoticeDto.java
  src/main/java/com/yapp/project/notice/domain/repository/NoticeRepository.java
  src/main/java/com/yapp/project/notice/service/NoticeService.java
  src/main/resources/import.sql
  src/test/java/com/yapp/project/notice/domain/repository/NoticeRepositoryTest.java
  src/test/java/com/yapp/project/notice/service/NoticeServiceTest.java
Labels: SCAFFOLDING:building_construction:

#109 [YAPPIOS-189] 참여자 갯수 ONETOMANY에서 배치 작업으로 변환
  src/main/java/com/yapp/project/batch/job/OrganizationConfig.java
  src/main/java/com/yapp/project/batch/scheduler/OrganizationScheduler.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
  src/main/java/com/yapp/project/mission/service/MissionService.java
  src/main/java/com/yapp/project/organization/domain/Organization.java
  src/test/java/com/yapp/project/batch/job/OrganizationConfigTest.java
  src/test/java/com/yapp/project/batch/job/TestBatchLegacyConfig.java
  src/test/java/com/yapp/project/organization/domain/repository/OrganizationRepositoryTest.java
Labels: :construction:Refactoring:construction:

#110 [YAPPIOS-210] 월 리포트 조회 카테고리별 비율 추가 및 응답 형식 수정
  src/main/java/com/yapp/project/report/controller/ReportController.java
  src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
  src/test/java/com/yapp/project/report/MonthReportServiceTest.java
Labels: :construction:Refactoring:construction:

#111 [YAPPIOS-211] 카테고리 Enum으로 변환 및 그룹 및 미션 필드 추가
  src/main/java/com/yapp/project/aux/test/organization/OrganizationTemplate.java
  src/main/java/com/yapp/project/batch/job/GroupNotificationConfig.java
  src/main/java/com/yapp/project/config/SecurityConfig.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/mission/domain/dto/MissionDto.java
  src/main/java/com/yapp/project/notice/controller/NoticeController.java
  src/main/java/com/yapp/project/organization/controller/CategoryController.java
  src/main/java/com/yapp/project/organization/controller/OrganizationController.java
  src/main/java/com/yapp/project/organization/domain/Category.java
  src/main/java/com/yapp/project/organization/domain/Organization.java
  src/main/java/com/yapp/project/organization/domain/dto/OrgDto.java
  src/main/java/com/yapp/project/organization/domain/repository/OrganizationRepository.java
  src/main/java/com/yapp/project/organization/service/CategoryService.java
  src/main/java/com/yapp/project/organization/service/GroupService.java
  src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
  src/main/resources/import.sql
  src/test/java/com/yapp/project/mission/service/MissionServiceTest.java
  src/test/java/com/yapp/project/organization/domain/OrganizationTest.java
  src/test/java/com/yapp/project/organization/domain/repository/OrganizationRepositoryTest.java
  src/test/java/com/yapp/project/organization/service/GroupServiceTest.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
Labels: :construction:Refactoring:construction:, :hammer_and_pick:클라이언트 작업 필요:hammer_and_pick:

#112 [YAPPIOS-214] 카테고리 타입 변경으로 인한 리팩토링
  src/main/java/com/yapp/project/report/controller/ReportController.java
  src/main/java/com/yapp/project/report/domain/MonthRoutineReport.java
  src/main/java/com/yapp/project/report/domain/RoutineResult.java
  src/main/java/com/yapp/project/report/domain/WeekReport.java
  src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
  src/main/java/com/yapp/project/report/service/ReportService.java
  src/main/java/com/yapp/project/routine/domain/Routine.java
  src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
  src/main/java/com/yapp/project/routine/domain/RoutineRepository.java
  src/test/java/com/yapp/project/report/MonthReportServiceTest.java
  src/test/java/com/yapp/project/report/WeekReportServiceTest.java
  src/test/java/com/yapp/project/report/template/MonthReportTemplate.java
  src/test/java/com/yapp/project/report/template/WeekReportTemplate.java
  src/test/java/com/yapp/project/retrospect/RetrospectServiceTest.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
  src/test/java/com/yapp/project/routine/RoutineTemplate.java
Labels: :construction:Refactoring:construction:

#113 [YAPPIOS-228] 카테고리-루틴 Enum작업 및 루틴,회고, 리포트 파트에 반영
  src/main/java/com/yapp/project/report/domain/MonthRoutineReport.java
  src/main/java/com/yapp/project/report/domain/RoutineResult.java
  src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
  src/main/java/com/yapp/project/routine/domain/Routine.java
  src/main/java/com/yapp/project/routine/domain/RoutineCategory.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
  src/test/java/com/yapp/project/report/MonthReportServiceTest.java
  src/test/java/com/yapp/project/report/template/MonthReportTemplate.java
  src/test/java/com/yapp/project/retrospect/RetrospectServiceTest.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
Labels: :construction:Refactoring:construction:

#114 [YAPPIOS-231] 루틴 응답 DTO 수정
  src/main/java/com/yapp/project/routine/controller/RoutineController.java
  src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
  src/main/java/com/yapp/project/routine/domain/RoutineRepository.java
  src/main/java/com/yapp/project/routine/domain/Week.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
Labels: :construction:Refactoring:construction:, :bangbang:긴급 추가:bangbang:

#115 [YAPPIOS-232] CloudStorage Util 구현 및 Retrospect 연결
  .gitignore
  build.gradle
  jenkinsfiles/Jenkinsfile_develop
  src/main/java/com/yapp/project/aux/common/SnapShotUtil.java
  src/main/java/com/yapp/project/aux/storage/CloudStorageUtil.java
  src/main/java/com/yapp/project/batch/scheduler/GroupScheduler.java
  src/main/java/com/yapp/project/batch/scheduler/MissionNotificationScheduler.java
  src/main/java/com/yapp/project/batch/scheduler/MissionScheduler.java
  src/main/java/com/yapp/project/batch/scheduler/OrganizationScheduler.java
  src/main/java/com/yapp/project/batch/scheduler/ReportNotificationScheduler.java
  src/main/java/com/yapp/project/batch/scheduler/ReportScheduler.java
  src/main/java/com/yapp/project/retrospect/controller/RetrospectController.java
  src/main/java/com/yapp/project/retrospect/service/RetrospectService.java
  src/test/java/com/yapp/project/retrospect/RetrospectServiceTest.java
Labels: SCAFFOLDING:building_construction:, :construction:Refactoring:construction:

#116 [YAPPIOS-233] @RequestBody 생략으로 인한 500에러 확인
  src/main/java/com/yapp/project/account/controller/AccountController.java
  src/main/java/com/yapp/project/account/controller/AuthController.java
  src/main/java/com/yapp/project/capture/controller/CaptureController.java
  src/main/java/com/yapp/project/mission/controller/MissionController.java
  src/main/java/com/yapp/project/saying/controller/SayingController.java
Labels: :hammer_and_pick:클라이언트 작업 필요:hammer_and_pick:, :bangbang:긴급 추가:bangbang:

#117 [YAPPIOS-234] 이미지 구글 스토리지로 넘어나는 것에 따른 변경
  src/main/java/com/yapp/project/capture/controller/CaptureController.java
  src/main/java/com/yapp/project/capture/service/CaptureService.java
  src/main/resources/static/test.jpeg
  src/test/java/com/yapp/project/capture/service/CaptureServiceTest.java
Labels: :construction:Refactoring:construction:

#118 [YAPPIOS-228] 루틴 응답 DTO 통일 리팩토링
  src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
Labels: :construction:Refactoring:construction:, :bangbang:긴급 추가:bangbang:

#120 [YAPPIOS-236] PrePersist 에 대한 문서 작업
  docs/pr_108.md
Labels: 문서작업

#121 [YAPPIOS-237] 월 리포트 조회 추가적인 예외 케이스 대응
  src/main/java/com/yapp/project/report/controller/ReportController.java
  src/main/java/com/yapp/project/report/domain/WeekReport.java
  src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
  src/main/java/com/yapp/project/report/service/ReportService.java
  src/test/java/com/yapp/project/report/MonthReportServiceTest.java
  src/test/java/com/yapp/project/report/WeekReportServiceTest.java
  src/test/java/com/yapp/project/report/template/MonthReportTemplate.java
Labels: :construction:Refactoring:construction:, 데이터베이스 변화 필요

#122 [YAPPIOS-239] 응답DTO 에 대한 문서 작업
  docs/pr_3.md
Labels: 문서작업

#123 [YAPPIOS-240] 카테고리 null 문제 해결
  src/main/java/com/yapp/project/organization/domain/Organization.java
  src/test/java/com/yapp/project/organization/service/GroupServiceTest.java
Labels: :hammer_and_pick:클라이언트 작업 필요:hammer_and_pick:, :bangbang:긴급 추가:bangbang:

#124 [YAPPIOS-238] JPA를 쓸 때 기본적으로 LAZY 전략으로 무조건 써야한다고 해서 바꿈
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/capture/domain/Capture.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/notice/domain/Notice.java
  src/main/java/com/yapp/project/notification/domain/Notification.java
  src/main/java/com/yapp/project/organization/domain/Organization.java
  src/main/java/com/yapp/project/report/domain/MonthRoutineReport.java
  src/main/java/com/yapp/project/report/domain/RetrospectReportDay.java
  src/main/java/com/yapp/project/report/domain/RoutineResult.java
  src/main/java/com/yapp/project/retrospect/domain/Retrospect.java
  src/main/java/com/yapp/project/routine/domain/RoutineDay.java
  src/main/java/com/yapp/project/saying/domain/Saying.java
  src/main/java/com/yapp/project/saying/domain/SayingRecord.java
Labels: :construction:Refactoring:construction:

#125 [YAPPIOS-242] 닉네임 중복 허용
  src/main/java/com/yapp/project/account/domain/Account.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
Labels: :hammer_and_pick:클라이언트 작업 필요:hammer_and_pick:, :bangbang:긴급 추가:bangbang:

#126 [YAPPIOS-243] 회고 삭제 시 루틴 수행 여부 보존하도록 수정
  src/main/java/com/yapp/project/aux/content/ReportContent.java
  src/main/java/com/yapp/project/retrospect/domain/Retrospect.java
  src/main/java/com/yapp/project/retrospect/service/RetrospectService.java
Labels: :construction:Refactoring:construction:

#127 [YAPPIOS-244] 내 mission 정보를 줄 때 오늘 미션 인증을 했는지 안 했는지 정보 표시 여부 전달
  src/main/java/com/yapp/project/capture/domain/repository/CaptureRepository.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/mission/domain/dto/MissionDto.java
  src/main/java/com/yapp/project/mission/service/MissionService.java
  src/test/java/com/yapp/project/mission/service/MissionServiceTest.java
Labels: :hammer_and_pick:클라이언트 작업 필요:hammer_and_pick:, :bangbang:긴급 추가:bangbang:
