Repository YAPP-19th/iOS-Team-1-Backend, pull requests merged in 2021-11, with the labels that each got.

#61 [YAPPIOS-127] slack 연동 작업
  build.gradle
  src/main/java/com/yapp/project/aux/AlertService.java
  src/main/java/com/yapp/project/batch/scheduler/GroupScheduler.java
  src/main/java/com/yapp/project/config/AppConfig.java
  src/main/java/com/yapp/project/config/exception/GlobalExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/account/AccountExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/capture/CaptureExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/mission/MissionExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/report/WeekReportExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/retrospect/RetrospectExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/routine/RoutineExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/saying/SayingExceptionHandler.java
Labels: :construction:Refactoring:construction:

#60 [YAPPIOS-125] 루틴 일별 수행률 응답 구현
  src/main/java/com/yapp/project/aux/StatusEnum.java
  src/main/java/com/yapp/project/aux/content/ReportContent.java
  src/main/java/com/yapp/project/aux/test/routine/RoutineTemplate.java
  src/main/java/com/yapp/project/config/exception/report/RoutineStartDayBadRequestException.java
  src/main/java/com/yapp/project/config/exception/report/WeekReportExceptionHandler.java
  src/main/java/com/yapp/project/report/controller/ReportController.java
  src/main/java/com/yapp/project/report/domain/WeekReport.java
  src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
  src/main/java/com/yapp/project/report/service/ReportService.java
  src/main/java/com/yapp/project/retrospect/domain/Retrospect.java
  src/main/java/com/yapp/project/retrospect/domain/RetrospectRepository.java
  src/main/java/com/yapp/project/routine/controller/RoutineController.java
  src/main/java/com/yapp/project/routine/domain/Routine.java
  src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
  src/main/java/com/yapp/project/routine/domain/RoutineRepository.java
  src/main/java/com/yapp/project/routine/domain/Week.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
  src/test/java/com/yapp/project/report/ReportServiceTest.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
Labels: SCAFFOLDING:building_construction:

#64 [YAPPIOS-101] 주리포트 디자인 변경으로 인한 로직 수정 및 조회 API 구현
  src/main/java/com/yapp/project/aux/StatusEnum.java
  src/main/java/com/yapp/project/aux/content/ReportContent.java
  src/main/java/com/yapp/project/config/exception/report/WeekReportExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/report/WeekReportNotFoundMonthException.java
  src/main/java/com/yapp/project/report/controller/ReportController.java
  src/main/java/com/yapp/project/report/domain/RoutineReportDay.java
  src/main/java/com/yapp/project/report/domain/RoutineResult.java
  src/main/java/com/yapp/project/report/domain/WeekReport.java
  src/main/java/com/yapp/project/report/domain/WeekReportRepository.java
  src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
  src/main/java/com/yapp/project/report/service/ReportService.java
Labels: SCAFFOLDING:building_construction:, :construction:Refactoring:construction:

#65 [YAPPIOS-107] 유저 삭제시 루틴, 주-월리포트 관계 끊기
  src/main/java/com/yapp/project/account/service/AccountService.java
  src/main/java/com/yapp/project/report/domain/MonthRoutineReport.java
  src/main/java/com/yapp/project/report/domain/MonthRoutineReportRepository.java
  src/main/java/com/yapp/project/report/domain/WeekReport.java
  src/main/java/com/yapp/project/report/domain/WeekReportRepository.java
  src/main/java/com/yapp/project/routine/domain/Routine.java
Labels: SCAFFOLDING:building_construction:

#66 [YAPPIOS-101] 주리포트 발급 로직(수행 여부 계산) 최적화
  src/main/java/com/yapp/project/aux/test/report/ReportTemplate.java
  src/main/java/com/yapp/project/report/domain/RoutineResult.java
  src/main/java/com/yapp/project/report/domain/WeekReport.java
  src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
  src/main/java/com/yapp/project/report/service/ReportService.java
Labels: :construction:Refactoring:construction:

#67 [YAPPIOS-130] 로깅 개선 작업
  src/main/java/com/yapp/project/batch/job/GroupConfig.java
  src/main/java/com/yapp/project/batch/scheduler/GroupScheduler.java
Labels: :construction:Refactoring:construction:

#68 [YAPPIOS-130] 채널 분리
  src/main/java/com/yapp/project/aux/alert/AlertService.java
  src/main/java/com/yapp/project/aux/alert/SlackChannel.java
  src/main/java/com/yapp/project/batch/job/GroupConfig.java
  src/main/java/com/yapp/project/batch/scheduler/GroupScheduler.java
  src/main/java/com/yapp/project/config/exception/GlobalExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/account/AccountExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/capture/CaptureExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/mission/MissionExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/report/WeekReportExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/retrospect/RetrospectExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/routine/RoutineExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/saying/SayingExceptionHandler.java
Labels: :construction:Refactoring:construction:

#70 [YAPPIOS-132] batch table sql 작성완료
  src/main/resources/schema.sql
Labels: :bangbang:긴급 추가:bangbang:

#71 [YAPPIOS-132] sql문 수정 및 배치 테스트를 위해 주기적으로 실행
  src/main/java/com/yapp/project/batch/scheduler/GroupScheduler.java
  src/main/resources/import.sql
Labels: :bangbang:긴급 추가:bangbang:

#72 [YAPPIOS-133] 소셜 토큰 KAKAO 받아 왔을 때 인증처리 로직 추가
  src/main/java/com/yapp/project/account/domain/dto/SocialDto.java
  src/main/java/com/yapp/project/account/domain/oauth/SocialProperty.java
  src/main/java/com/yapp/project/account/domain/oauth/kakao/KakaoResponse.java
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/main/java/com/yapp/project/aux/request/ApiService.java
  src/main/java/com/yapp/project/config/RestTemplateConfig.java
Labels: SCAFFOLDING:building_construction:, :construction:Refactoring:construction:

#74 [YAPPIOS-138] APPLE 인증 토큰 관련 처리
  src/main/java/com/yapp/project/account/domain/dto/SocialDto.java
  src/main/java/com/yapp/project/account/domain/oauth/apple/AppleKeyStorage.java
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/main/java/com/yapp/project/aux/content/AccountContent.java
  src/main/java/com/yapp/project/aux/request/ApiService.java
  src/main/java/com/yapp/project/config/exception/account/AccountExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/account/SocialTokenInvalidException.java
Labels: SCAFFOLDING:building_construction:, :construction:Refactoring:construction:

#73 [YAPPIOS-123] 주리포트 발급 4주치 시나리오 단위 테스트 작성 및 테스트를 위한 템플릿 위치 이동
  build.gradle
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/aux/common/DateUtil.java
  src/main/java/com/yapp/project/report/service/ReportService.java
  src/test/java/com/yapp/project/report/MonthReportServiceTest.java
  src/test/java/com/yapp/project/report/WeekReportServiceTest.java
  src/test/java/com/yapp/project/report/template/MonthReportTemplate.java
  src/test/java/com/yapp/project/report/template/WeekReportTemplate.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
  src/test/java/com/yapp/project/routine/RoutineTemplate.java
Labels: SCAFFOLDING:building_construction:, :construction:Refactoring:construction:

#75 [YAPPIOS-142] 캡처 날짜 확인하는 로직 추가
  src/main/java/com/yapp/project/aux/content/CaptureContent.java
  src/main/java/com/yapp/project/capture/service/CaptureService.java
  src/main/java/com/yapp/project/config/exception/capture/CaptureExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/capture/NotTodayCaptureException.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/report/service/ReportService.java
  src/main/java/com/yapp/project/retrospect/service/RetrospectService.java
  src/main/java/com/yapp/project/routine/domain/Week.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
  src/test/java/com/yapp/project/capture/service/CaptureServiceTest.java
Labels: SCAFFOLDING:building_construction:, :construction:Refactoring:construction:

#76 [YAPPIOS-143] 미션 실패 관련 배치 작업 설정
  src/main/java/com/yapp/project/batch/job/MissionConfig.java
  src/main/java/com/yapp/project/batch/scheduler/GroupScheduler.java
  src/main/java/com/yapp/project/batch/scheduler/MissionScheduler.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/test/java/com/yapp/project/batch/job/GroupConfigTest.java
  src/test/java/com/yapp/project/batch/job/MissionConfigTest.java
  src/test/java/com/yapp/project/batch/job/TestBatchLegacyConfig.java
Labels: SCAFFOLDING:building_construction:, :construction:Refactoring:construction:

#77 [YAPPIOS-122] 주 리포트와 월 리포트 배치 전략 설계 및 적용
  src/main/java/com/yapp/project/batch/job/ReportConfig.java
  src/main/java/com/yapp/project/batch/scheduler/ReportScheduler.java
  src/main/java/com/yapp/project/batch/scheduler/SchedulerConfig.java
  src/main/java/com/yapp/project/report/service/ReportService.java
  src/main/java/com/yapp/project/retrospect/service/RetrospectService.java
Labels: SCAFFOLDING:building_construction:, :construction:Refactoring:construction:

#78 [YAPPIOS-140, 141] Firebase Cloud Message Util 구현 및 리포트 알림 적용
  .DS_Store
  .gitignore
  build.gradle
  src/main/java/com/yapp/project/aux/fcm/FireBaseCloudMessage.java
  src/main/java/com/yapp/project/aux/fcm/FireBaseCloudMessageService.java
  src/main/java/com/yapp/project/batch/job/ReportNotificationConfig.java
  src/main/java/com/yapp/project/batch/scheduler/ReportNotificationScheduler.java
Labels: SCAFFOLDING:building_construction:, :hammer_and_pick:클라이언트 작업 필요:hammer_and_pick:

#79 [YAPPIOS-147] 회고 작성 요일(당일 포함 3일) 아닐경우 예외처리
  src/main/java/com/yapp/project/retrospect/domain/dto/RetrospectDTO.java
  src/main/java/com/yapp/project/retrospect/service/RetrospectService.java
  src/test/java/com/yapp/project/retrospect/RetrospectServiceTest.java
Labels: :construction:Refactoring:construction:

#80 [YAPPIOS-148][YAPPIOS-149] 루틴 요일 변경시, 기 작성된 회고 처리 로직 추가 및 루틴 서비스로직 트랜잭션 적용
  src/main/java/com/yapp/project/report/service/ReportService.java
  src/main/java/com/yapp/project/retrospect/domain/Retrospect.java
  src/main/java/com/yapp/project/retrospect/domain/RetrospectRepository.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
Labels: :construction:Refactoring:construction:

#81 [YAPPIOS-152] 명언 추가
  src/main/resources/import.sql
Labels: SCAFFOLDING:building_construction:

#82 [YAPPIOS-150][YAPPIOS-151] Routine 및 Retrospect 서비스 로직과 리포트 노티 관련 리팩토링
  .DS_Store
  jenkinsfiles/Jenkinsfile_develop
  src/main/java/com/yapp/project/aux/content/ReportContent.java
  src/main/java/com/yapp/project/batch/job/ReportNotificationConfig.java
  src/main/java/com/yapp/project/batch/scheduler/ReportNotificationScheduler.java
  src/main/java/com/yapp/project/batch/scheduler/ReportScheduler.java
  src/main/java/com/yapp/project/retrospect/service/RetrospectService.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
Labels: :construction:Refactoring:construction:

#83 [YAPPIOS-145] FCM 토큰 요청값 추가 작업 실시
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/main/java/com/yapp/project/account/util/PasswordUtil.java
  src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
  src/test/java/com/yapp/project/account/domain/dto/AccountUserSocialRequestDtoTest.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
  src/test/java/com/yapp/project/account/util/PasswordUtilTest.java
Labels: :construction:Refactoring:construction:

#85 [YAPPIOS-157] 필드 추가에 따른 에러 수정
  src/main/java/com/yapp/project/aux/test/mission/MissionTemplate.java
Labels: :bangbang:긴급 추가:bangbang:

#86 [YAPPIOS-162] 로그인 DTO 수정
  src/main/java/com/yapp/project/account/controller/AuthController.java
  src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
  src/main/java/com/yapp/project/account/domain/dto/SocialDto.java
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/test/java/com/yapp/project/account/controller/AuthControllerTest.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
Labels: :construction:Refactoring:construction:

#87 [YAPPIOS-169] 알람 필드 추가 및 기능 구현
  src/main/java/com/yapp/project/account/controller/AccountController.java
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/account/service/AccountService.java
  src/main/java/com/yapp/project/aux/content/AccountContent.java
  src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
  src/main/java/com/yapp/project/mission/service/MissionService.java
  src/test/java/com/yapp/project/account/service/AccountServiceTest.java
  src/test/java/com/yapp/project/mission/service/MissionServiceTest.java
Labels: SCAFFOLDING:building_construction:

#88 [YAPPIOS-178] 이메일 API 신설
  src/main/java/com/yapp/project/account/controller/AuthController.java
  src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
  src/main/java/com/yapp/project/account/service/AccountService.java
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/main/java/com/yapp/project/account/util/PasswordUtil.java
  src/main/java/com/yapp/project/account/util/RegexUtil.java
  src/main/java/com/yapp/project/aux/content/AccountContent.java
  src/main/java/com/yapp/project/config/exception/account/EmailInvalidException.java
  src/main/java/com/yapp/project/config/exception/account/PasswordInvalidException.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
  src/test/java/com/yapp/project/account/util/RegexUtilTest.java
Labels: SCAFFOLDING:building_construction:

#89 [YAPPIOS-179] 이메일 에러 핸들러 추가 및 APPLE KEY 관련 에러 범위 확장
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/main/java/com/yapp/project/config/exception/account/AccountExceptionHandler.java
Labels: :construction:Refactoring:construction:

#90 [YAPPIOS-166] 그룹 디테일 내용 추가
  src/main/java/com/yapp/project/aux/test/organization/OrganizationTemplate.java
  src/main/java/com/yapp/project/organization/domain/Clause.java
  src/main/java/com/yapp/project/organization/domain/Organization.java
  src/main/java/com/yapp/project/organization/domain/dto/OrgDto.java
  src/main/resources/import.sql
Labels: :construction:Refactoring:construction:

#91 [YAPPIOS-181] 그룹 관련 sql 수정 및 @Lob 설정 추가
  src/main/java/com/yapp/project/organization/domain/Organization.java
  src/main/resources/import.sql
Labels: :construction:Refactoring:construction:

#92 [YAPPIOS-124] 추천루틴 응답 API 구현
  src/main/java/com/yapp/project/aux/StatusEnum.java
  src/main/java/com/yapp/project/routine/controller/RoutineController.java
  src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
Labels: SCAFFOLDING:building_construction:

#93 [YAPPIOS-180] 노티 여부 설정에 따른 리포트 노티 및 부가요소 리팩토링
  src/main/java/com/yapp/project/account/domain/repository/AccountRepository.java
  src/main/java/com/yapp/project/aux/content/ReportContent.java
  src/main/java/com/yapp/project/aux/content/RoutineContent.java
  src/main/java/com/yapp/project/aux/fcm/FireBaseCloudMessageService.java
  src/main/java/com/yapp/project/batch/job/ReportNotificationConfig.java
  src/main/java/com/yapp/project/routine/domain/RoutineDTO.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
Labels: :construction:Refactoring:construction:

#94 [YAPPIOS-182] Remove 기능 폐기, 영구삭제로 전환
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/account/service/AccountService.java
  src/main/java/com/yapp/project/aux/common/AccountUtil.java
  src/main/java/com/yapp/project/batch/job/MissionConfig.java
  src/main/java/com/yapp/project/capture/controller/CaptureController.java
  src/main/java/com/yapp/project/capture/domain/Capture.java
  src/main/java/com/yapp/project/capture/domain/CaptureImage.java
  src/main/java/com/yapp/project/capture/domain/repository/CaptureRepository.java
  src/main/java/com/yapp/project/capture/service/CaptureService.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
  src/main/java/com/yapp/project/mission/service/MissionService.java
  src/test/java/com/yapp/project/account/service/AccountServiceTest.java
  src/test/java/com/yapp/project/batch/job/GroupConfigTest.java
  src/test/java/com/yapp/project/capture/service/CaptureServiceTest.java
  src/test/java/com/yapp/project/mission/service/MissionServiceTest.java
Labels: :construction:Refactoring:construction:
