Repository YAPP-19th/iOS-Team-1-Backend, pull requests merged in 2021-10, with the labels that each got.

#5 [YAPPIOS-23] 테스트케이스 추가 및 에러 메세지 하나의 클래스에 통합
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/main/java/com/yapp/project/config/exception/Content.java
  src/test/java/com/yapp/project/account/controller/AuthControllerTest.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
Labels: SCAFFOLDING:building_construction:, :white_check_mark:TEST:white_check_mark:

#11 [YAPPIOS-36] 그룹 관련 스케치 작업
  src/main/java/com/yapp/project/organization/domain/Organization.java
  src/main/java/com/yapp/project/organization/domain/dto/OrganizationDto.java
  src/main/java/com/yapp/project/organization/service/GroupService.java
Labels: SCAFFOLDING:building_construction:

#13 [YAPPIOS-37] DTO 통합처리
  src/main/java/com/yapp/project/account/controller/AccountController.java
  src/main/java/com/yapp/project/account/controller/AuthController.java
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
  src/main/java/com/yapp/project/account/domain/dto/AccountRequestDto.java
  src/main/java/com/yapp/project/account/domain/dto/AccountResponseDto.java
  src/main/java/com/yapp/project/account/domain/dto/NicknameRequestDto.java
  src/main/java/com/yapp/project/account/domain/dto/SocialDto.java
  src/main/java/com/yapp/project/account/domain/dto/SocialRequestDto.java
  src/main/java/com/yapp/project/account/domain/dto/SocialResponseDto.java
  src/main/java/com/yapp/project/account/domain/dto/SocialSignUpRequestDto.java
  src/main/java/com/yapp/project/account/service/AccountService.java
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/main/java/com/yapp/project/aux/note/account/AccountNotes.java
  src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
  src/test/java/com/yapp/project/account/controller/AccountControllerTest.java
  src/test/java/com/yapp/project/account/controller/AuthControllerTest.java
  src/test/java/com/yapp/project/account/domain/dto/AccountRequestDtoTest.java
  src/test/java/com/yapp/project/account/service/AccountServiceTest.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
Labels: :construction:Refactoring:construction:

#15 [YAPPIOS-42] 도메인 - 2 작업
  src/main/java/com/yapp/project/base/Cron.java
  src/main/java/com/yapp/project/retrospect/domain/Retrospect.java
  src/main/java/com/yapp/project/routine/domain/Routine.java
  src/main/java/com/yapp/project/snapshot/domain/Snapshot.java
Labels: SCAFFOLDING:building_construction:

#17 [YAPPIOS-42] Cron Entity Routine과 분리 및 RoutineDay Entity 작성
  src/main/java/com/yapp/project/mission/domain/Cron.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/routine/domain/Routine.java
  src/main/java/com/yapp/project/routine/domain/RoutineDay.java
Labels: :construction:Refactoring:construction:

#20 BUGFIX TESTCASE ERROR
  src/test/java/com/yapp/project/organization/domain/repository/OrganizationRepositoryTest.java
Labels: :warning:ISSUE:warning:, :white_check_mark:TEST:white_check_mark:

#22 [YAPPIOS-58] DTO 이름 변경
  src/main/java/com/yapp/project/account/controller/AccountController.java
  src/main/java/com/yapp/project/account/controller/AuthController.java
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
  src/main/java/com/yapp/project/account/domain/dto/SocialDto.java
  src/main/java/com/yapp/project/account/service/AccountService.java
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
  src/test/java/com/yapp/project/account/controller/AccountControllerTest.java
  src/test/java/com/yapp/project/account/controller/AuthControllerTest.java
  src/test/java/com/yapp/project/account/domain/dto/AccountUserSocialRequestDtoTest.java
  src/test/java/com/yapp/project/account/service/AccountServiceTest.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
Labels: :construction:Refactoring:construction:

#24 [YAPPIOS-53] 루틴 조회하기 API 구현
  src/main/java/com/yapp/project/config/exception/Content.java
  src/main/java/com/yapp/project/config/exception/routine/BadRequestException.java
  src/main/java/com/yapp/project/config/exception/routine/NotFoundRoutineException.java
  src/main/java/com/yapp/project/config/exception/routine/RoutineExceptionHandler.java
  src/main/java/com/yapp/project/routine/controller/RoutineController.java
  src/main/java/com/yapp/project/routine/domain/RoutineRepository.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
Labels: SCAFFOLDING:building_construction:

#25 [YAPPIOS-47] 루틴 수정 및 삭제 API 구현
  src/main/java/com/yapp/project/routine/controller/RoutineController.java
  src/main/java/com/yapp/project/routine/domain/Routine.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
Labels: SCAFFOLDING:building_construction:

#29 [YAPPIOS-65] 요일별 루틴 순서 편집 API 구현
  src/main/java/com/yapp/project/routine/controller/RoutineController.java
  src/main/java/com/yapp/project/routine/domain/Routine.java
  src/main/java/com/yapp/project/routine/domain/RoutineDay.java
  src/main/java/com/yapp/project/routine/service/RoutineService.java
  src/test/java/com/yapp/project/routine/RoutineServiceTest.java
Labels: SCAFFOLDING:building_construction:

#30 [YAPPIOS-67] 유저 비밀번호 정규식 강화
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/account/domain/SocialType.java
  src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/main/java/com/yapp/project/account/util/PasswordUtil.java
  src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
  src/main/java/com/yapp/project/config/exception/Content.java
  src/main/java/com/yapp/project/config/exception/account/NotValidateException.java
  src/test/java/com/yapp/project/account/domain/dto/AccountUserSocialRequestDtoTest.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
  src/test/java/com/yapp/project/saying/domain/SayingTest.java
Labels: :construction:Refactoring:construction:

#33 [YAPPIOS-72] 스웨거 문서 강화 작업 완료
  src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
  src/main/java/com/yapp/project/account/domain/dto/SocialDto.java
  src/main/java/com/yapp/project/account/domain/dto/TokenDto.java
  src/main/java/com/yapp/project/account/domain/dto/TokenRequestDto.java
  src/main/java/com/yapp/project/organization/domain/dto/OrgDto.java
  src/main/java/com/yapp/project/saying/domain/dto/SayingDto.java
Labels: :construction:Refactoring:construction:

#36 [YAPPIOS-75] 모델링 재작업
  src/main/java/com/yapp/project/mission/domain/Achievement.java
  src/main/java/com/yapp/project/mission/domain/Capture.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
Labels: :construction:Refactoring:construction:

#37 [YAPPIOS-66] 미션 관련 기능 구현 및 수정
  src/main/java/com/yapp/project/aux/StatusEnum.java
  src/main/java/com/yapp/project/aux/test/mission/MissionTemplate.java
  src/main/java/com/yapp/project/aux/test/organization/OrganizationTemplate.java
  src/main/java/com/yapp/project/config/exception/mission/AlreadyMissionExistException.java
  src/main/java/com/yapp/project/config/exception/mission/MissionContent.java
  src/main/java/com/yapp/project/config/exception/mission/MissionNotFoundException.java
  src/main/java/com/yapp/project/mission/controller/MissionController.java
  src/main/java/com/yapp/project/mission/domain/Capture.java
  src/main/java/com/yapp/project/mission/domain/Cron.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/mission/domain/MissionCount.java
  src/main/java/com/yapp/project/mission/domain/dao/MissionOrganization.java
  src/main/java/com/yapp/project/mission/domain/dto/MissionDto.java
  src/main/java/com/yapp/project/mission/domain/repository/CaptureRepository.java
  src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
  src/main/java/com/yapp/project/mission/service/MissionService.java
  src/main/java/com/yapp/project/mission/utils/DateUtils.java
  src/main/java/com/yapp/project/organization/controller/OrganizationController.java
  src/main/java/com/yapp/project/organization/domain/Organization.java
  src/main/java/com/yapp/project/organization/domain/dto/OrgDto.java
  src/main/java/com/yapp/project/organization/domain/repository/OrganizationRepository.java
  src/main/java/com/yapp/project/organization/service/GroupService.java
  src/main/java/com/yapp/project/snapshot/domain/Snapshot.java
  src/test/java/com/yapp/project/mission/service/MissionServiceTest.java
  src/test/java/com/yapp/project/organization/domain/repository/OrganizationRepositoryTest.java
  src/test/java/com/yapp/project/organization/service/GroupServiceTest.java
Labels: SCAFFOLDING:building_construction:, :construction:Refactoring:construction:

#40 [YAPPIOS-80] 명언 오늘 했는 지 확인하는 기능 추가
  src/main/java/com/yapp/project/saying/controller/SayingController.java
  src/main/java/com/yapp/project/saying/domain/dto/SayingDto.java
  src/main/java/com/yapp/project/saying/service/SayingService.java
  src/main/java/com/yapp/project/saying/utils/SayingUtils.java
  src/test/java/com/yapp/project/saying/service/SayingServiceTest.java
Labels: SCAFFOLDING:building_construction:, :construction:Refactoring:construction:

#44 [YAPPIOS-80] 명시화 작업
  src/main/java/com/yapp/project/account/controller/AccountController.java
  src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/main/java/com/yapp/project/account/util/SecurityUtil.java
  src/main/java/com/yapp/project/aux/content/AccountContent.java
  src/main/java/com/yapp/project/mission/domain/dto/MissionDto.java
  src/main/java/com/yapp/project/mission/service/MissionService.java
  src/main/java/com/yapp/project/organization/controller/OrganizationController.java
  src/main/java/com/yapp/project/organization/domain/dto/OrgDto.java
  src/main/java/com/yapp/project/organization/service/GroupService.java
  src/main/java/com/yapp/project/saying/service/SayingService.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
Labels: :construction:Refactoring:construction:

#54 [YAPPIOS-98] 3일 지난 회고 수정 불가 적용(ex 27일 작성 회고는 29일까지 수정 가능)
  src/main/java/com/yapp/project/config/exception/retrospect/InvalidRetrospectUpdateException.java
  src/main/java/com/yapp/project/config/exception/retrospect/RetrospectContent.java
  src/main/java/com/yapp/project/config/exception/retrospect/RetrospectExceptionHandler.java
  src/main/java/com/yapp/project/retrospect/service/RetrospectService.java
Labels: :construction:Refactoring:construction:

#55 [YAPPIOS-91] 배치 기능 추가
  build.gradle
  src/main/java/com/yapp/project/ProjectApplication.java
  src/main/java/com/yapp/project/aux/common/DateUtil.java
  src/main/java/com/yapp/project/batch/job/GroupConfig.java
  src/main/java/com/yapp/project/batch/scheduler/GroupScheduler.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
  src/main/java/com/yapp/project/organization/domain/Organization.java
  src/main/resources/import.sql
  src/test/java/com/yapp/project/account/controller/AuthControllerTest.java
  src/test/java/com/yapp/project/account/service/AccountServiceTest.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
  src/test/java/com/yapp/project/batch/job/GroupConfigTest.java
  src/test/java/com/yapp/project/batch/job/TestBatchLegacyConfig.java
  src/test/java/com/yapp/project/organization/domain/repository/OrganizationRepositoryTest.java
Labels: :construction:Refactoring:construction:

#56 [YAPPIOS-94] 종료된 미션 리스트 보여주기
  src/main/java/com/yapp/project/aux/common/DateUtil.java
  src/main/java/com/yapp/project/aux/content/MissionContent.java
  src/main/java/com/yapp/project/aux/test/mission/MissionTemplate.java
  src/main/java/com/yapp/project/mission/controller/MissionController.java
  src/main/java/com/yapp/project/mission/domain/Mission.java
  src/main/java/com/yapp/project/mission/domain/dto/MissionDto.java
  src/main/java/com/yapp/project/mission/domain/repository/MissionRepository.java
  src/main/java/com/yapp/project/mission/service/MissionService.java
  src/main/java/com/yapp/project/mission/utils/DateUtils.java
  src/test/java/com/yapp/project/mission/service/MissionServiceTest.java
Labels: SCAFFOLDING:building_construction:, :construction:Refactoring:construction:

#57 [YAPPIOS-100] 월 리포트 발급 비즈니스 로직 및 응답 API 구현
  build.gradle
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/aux/StatusEnum.java
  src/main/java/com/yapp/project/aux/content/ReportContent.java
  src/main/java/com/yapp/project/aux/content/WeekReportContent.java
  src/main/java/com/yapp/project/aux/test/account/AccountTemplate.java
  src/main/java/com/yapp/project/aux/test/report/ReportTemplate.java
  src/main/java/com/yapp/project/config/exception/report/AlreadyWeekReportFoundException.java
  src/main/java/com/yapp/project/config/exception/report/MonthReportNotFoundMonthException.java
  src/main/java/com/yapp/project/config/exception/report/WeekReportExceptionHandler.java
  src/main/java/com/yapp/project/report/controller/ReportController.java
  src/main/java/com/yapp/project/report/domain/MonthRoutineReport.java
  src/main/java/com/yapp/project/report/domain/MonthRoutineReportRepository.java
  src/main/java/com/yapp/project/report/domain/RetrospectReportDay.java
  src/main/java/com/yapp/project/report/domain/RoutineReportDay.java
  src/main/java/com/yapp/project/report/domain/RoutineResult.java
  src/main/java/com/yapp/project/report/domain/WeekReport.java
  src/main/java/com/yapp/project/report/domain/WeekReportRepository.java
  src/main/java/com/yapp/project/report/domain/dto/ReportDTO.java
  src/main/java/com/yapp/project/report/service/ReportService.java
  src/main/java/com/yapp/project/weekReport/controller/WeekReportController.java
  src/main/java/com/yapp/project/weekReport/domain/WeekReportRepository.java
  src/main/java/com/yapp/project/weekReport/service/WeekReportService.java
  src/test/java/com/yapp/project/report/ReportServiceTest.java
Labels: SCAFFOLDING:building_construction:

#58 [YAPPIOS-120] 닉네임 중복 체크 안하고 글자수 6글자 반영
  src/main/java/com/yapp/project/account/controller/AuthController.java
  src/main/java/com/yapp/project/account/domain/Account.java
  src/main/java/com/yapp/project/account/domain/dto/AccountDto.java
  src/main/java/com/yapp/project/account/service/AuthService.java
  src/main/java/com/yapp/project/aux/content/AccountContent.java
  src/main/java/com/yapp/project/config/exception/account/AccountExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/account/NicknameLengthOverException.java
  src/test/java/com/yapp/project/account/service/AuthServiceTest.java
Labels: :construction:Refactoring:construction:

#59 [YAPPIOS-121] 센트리 연결 및 설정 변경
  build.gradle
  src/main/java/com/yapp/project/capture/controller/CaptureController.java
  src/main/java/com/yapp/project/config/exception/GlobalExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/account/AccountExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/capture/CaptureExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/mission/MissionExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/report/WeekReportExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/retrospect/RetrospectExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/routine/RoutineExceptionHandler.java
  src/main/java/com/yapp/project/config/exception/saying/SayingExceptionHandler.java
  src/main/java/com/yapp/project/retrospect/controller/RetrospectController.java
Labels: SCAFFOLDING:building_construction:
